# Clippy configuration file
# You can enable or disable lints, and configure specific linting rules

# Disable a specific lint
blacklisted-name = "allow"

# Set the cyclomatic complexity that you consider acceptable in your code
cyclomatic-complexity-threshold = 10
