name: Rust CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    timeout-minutes: 60  # Set a timeout

    container:
      image: archlinux:latest
      env:
        HOME: /github/home

    steps:
      - name: Setup system
        run: |
          pacman -Syu --noconfirm
          pacman -S --noconfirm base-devel

      - name: Checkout code
        uses: actions/checkout@v3  # Update to v3

      - name: Add Cargo bin to PATH
        run: echo "$HOME/.cargo/bin" >> $GITHUB_PATH


      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1  # Update to the latest version that supports Node 16
        with:
          profile: minimal
          toolchain: nightly
          override: true

      - name: Build
        run: cargo build --verbose
        working-directory: ./

      - name: Test
        run: cargo test --verbose
        working-directory: ./

      - name: Install Clippy
        run: rustup component add clippy

      - name: Clippy
        run: cargo clippy --verbose -- -D warnings

      - name: Install Rustfmt
        run: rustup component add rustfmt

      - name: Rustfmt
        run: cargo fmt --all -- --check

      - name: Install cargo-audit
        run: cargo install cargo-audit

      - name: Audit dependencies
        run: cargo audit

      - name: Upload artifact
        uses: actions/upload-artifact@v4  # Update to the latest version that supports Node 16
        with:
          name: build-artifact
          path: ./target
