name: Rust CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  setup:
    runs-on: ubuntu-latest  # Use the default GitHub runner

    container:
      image: archlinux:latest  # Use the latest Arch Linux Docker image
      env:
        HOME: /root  # Set the $HOME environment variable to /root

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

  build:
    needs: setup
    runs-on: ubuntu-latest  # Use the default GitHub runner

    container:
      image: archlinux:latest  # Use the latest Arch Linux Docker image
      env:
        HOME: /root  # Set the $HOME environment variable to /root

    steps:
      - name: Build
        run: cargo build --verbose

  test:
    needs: build
    runs-on: ubuntu-latest  # Use the default GitHub runner

    container:
      image: archlinux:latest  # Use the latest Arch Linux Docker image
      env:
        HOME: /root  # Set the $HOME environment variable to /root

    steps:
      - name: Test
        run: cargo test --verbose

  lint:
    needs: test
    runs-on: ubuntu-latest  # Use the default GitHub runner

    container:
      image: archlinux:latest  # Use the latest Arch Linux Docker image
      env:
        HOME: /root  # Set the $HOME environment variable to /root

    steps:
      - name: Clippy
        run: cargo clippy --verbose -- -D warnings

      - name: Rustfmt
        run: cargo fmt --all -- --check

  audit:
    needs: lint
    runs-on: ubuntu-latest  # Use the default GitHub runner

    container:
      image: archlinux:latest  # Use the latest Arch Linux Docker image
      env:
        HOME: /root  # Set the $HOME environment variable to /root

    steps:
      - name: Install cargo-audit
        run: cargo install cargo-audit

      - name: Audit dependencies
        run: cargo audit
