name: Rust CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  setup:
    runs-on: ubuntu-latest  # Use the default GitHub runner

    container:
      image: archlinux:latest  # Use the latest Arch Linux Docker image

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Install cargo-audit
        run: cargo install cargo-audit

  build:
    needs: setup
    runs-on: ubuntu-latest  # Use the default GitHub runner

    container:
      image: archlinux:latest  # Use the latest Arch Linux Docker image

    steps:
      - name: Build
        run: cargo build --verbose

  test:
    needs: build
    runs-on: ubuntu-latest  # Use the default GitHub runner

    container:
      image: archlinux:latest  # Use the latest Arch Linux Docker image

    steps:
      - name: Test
        run: cargo test --verbose

  lint:
    needs: test
    runs-on: ubuntu-latest  # Use the default GitHub runner

    container:
      image: archlinux:latest  # Use the latest Arch Linux Docker image

    steps:
      - name: Clippy
        run: cargo clippy --verbose -- -D warnings
        env:
          # Assuming .clippy.toml is in the root of your repository
          CARGO_HOME: ${{ github.workspace }}

      - name: Rustfmt
        run: cargo fmt --all -- --check
        env:
          # Assuming .rustfmt.toml is in the root of your repository
          CARGO_HOME: ${{ github.workspace }}

  audit:
    needs: lint
    runs-on: ubuntu-latest  # Use the default GitHub runner

    container:
      image: archlinux:latest  # Use the latest Arch Linux Docker image

    steps:
      - name: Audit
        run: cargo audit --verbose
