name: Rust CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - name: Check Docker version
        run: docker --version

      - name: Clean up resources from previous jobs
        run: docker system prune -f

      - name: Create local container network
        run: docker network create github_network

      - name: Start job container
        run: |
          docker pull archlinux:latest
          docker run --network github_network --name job_container -d archlinux:latest tail -f /dev/null

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

  build:
    needs: setup
    runs-on: ubuntu-latest

    container:
      image: archlinux:latest
      env:
        HOME: /github/home

    steps:
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Build
        run: cargo build --verbose

  test:
    needs: build
    runs-on: ubuntu-latest

    container:
      image: archlinux:latest
      env:
        HOME: /github/home

    steps:
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Test
        run: cargo test --verbose

  lint:
    needs: test
    runs-on: ubuntu-latest

    container:
      image: archlinux:latest
      env:
        HOME: /github/home

    steps:
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Clippy
        run: cargo clippy --verbose -- -D warnings

      - name: Rustfmt
        run: cargo fmt --all -- --check

  audit:
    needs: lint
    runs-on: ubuntu-latest

    container:
      image: archlinux:latest
      env:
        HOME: /github/home

    steps:
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Install cargo-audit
        run: cargo install cargo-audit

      - name: Audit dependencies
        run: cargo audit
